[package]
name = "erc_7765_rwa_integration"
version = "0.1.0"
edition = "2024_07"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
starknet = ">2.8.0"
openzeppelin = { git = "https://github.com/openzeppelin/cairo-contracts", tag = "v0.17.0"  }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.14.0" }

[dev-dependencies]

[scripts]
test = "snforge test"


[[target.starknet-contract]]
allowed-libfuncs-list.name = "audited"
sierra = true
casm = true